# Konfiguracija servera
spring.application.name=iis
server.port=8080

spring.sql.init.encoding=UTF-8
jwt.secret=yoursecuresecretkeywhichissolovely
jwt.expiration=86400000

#Konfiguracije baze podataka
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/iis_db
spring.datasource.username=admin
spring.datasource.password=admin

# JPA/Hibernate konfiguracija
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Inicijalizacija podataka
#  - Da prokrene data.sql svaki put
spring.sql.init.mode=always
#  - Da napravi tabele pre nego sto pokusa da unese vrednosti
spring.jpa.defer-datasource-initialization=true